version: '2.1'

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  s3ls:
    executor: aws-cli/default
    steps:
      - aws-cli/assume_role_with_web_identity:
          role_arn: $AWS_ROLE_ARN
      - run: aws s3 ls s3://

workflows:
  oidc-test:
    jobs:
      - s3ls:
          context: aws-oidc
